Feature#2 entity생성
jiione/new-klas-BE pull request #3
Opened 2023-05-19 14:07 UTC by jiione

### Entity 생성
- Board
- Post
- Course
- Department
- Subjects
- User

2023-05-19 15:44 UTC, Icln requested changes
코드 작성 고생하셨습니다!!
전반적으로 양방향 관계를 사용하신 것 같은데 단방향 관계로 설정하시고 필요할 때만 
양방향 관계를 설정하시는 것이 좋아보입니다!!

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +public class BoardEntity {
`@Table 을 사용하지 않으면 클래스명이 테이블명이 되는 것으로 알고 있습니다.
따라서 table 이름을 따로 지정해주는 것이 좋아보입니다.
다른 엔티티도 마찬가지 입니다.
또한 클래스명 또한 entity를 붙이지 않는 것이 좋아보입니다!!

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +    @Column(name = "board_id")
해당 컬럼도 auto increment로 설정해야 하지 않나요??

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +    @ManyToOne
erd 상으로는 1 : 1인데 확인 부탁드립니다!

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +    @OneToMany(mappedBy = "board")
단방향이 아닌 양방향 관계로 설정하신 이유가 있을까요?

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/CouresEntityId.java
> +public class CouresEntityId implements Serializable {
복합키로 ERD가 설정되어서 이렇게 하신 것 같습니다!
하지만 테이블마다 단일 키로 설정하는 것이 좋다고 알고 있어서 이 부분도 후에 
회의를 통해 수정하는 것이 좋아보입니다!!

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/PostEntity.java
> +    @ManyToOne
fetchType을 Lazy로 설정하는 것이 좋아보입니다!

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/PostEntity.java
> +    private Timestamp time;
LocalDateTime이 아닌 해당 자료형을 사용하신 이유가 있을까요?

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/PostEntity.java
> +    private String view;
조회수는 Long 타입인 것 같습니다. ERD 확인 부탁드립니다

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/PostEntity.java
> +    @JoinColumn(name = "board_id")
여기도 마찬가지로 nullable과 updatable 같은 옵션을 넣어주면 좋을 것 같습니다

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/SubjectsEntity.java
> +    @OneToMany(mappedBy = "subjects")
여기도 양방향 관계를 사용하신 이유가 있을까요?

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/SubjectsEntity.java
> +    private String credit;
erd 상으로는 string이 되어있긴 하는데 해당 컬럼이 3학점인 수업인 것을 표현하기 위한 컬럼이면 string 보단 Integer가  좋은 것 같은데 어떻게 생각하시나요??

2023-05-19 15:44 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/UserEntity.java
> +    private String birth;
생년월일도 LocalDate를 사용하는 것이 더 좋아보이는데 어떻게 생각하시나요?

2023-05-20 11:56 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +public class BoardEntity {
@Icln 넵 @Table 붙여 전부 명명하겠습니다.
  @Table로 테이블 이름을 명시 했는데도 클래스 명에 entity를 제거 하나요?

2023-05-20 11:59 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +    @Column(name = "board_id")
@Icln 
<img width="381" alt="image" src="https://github.com/jiione/new-klas-BE/assets/83341978/9f84aaa8-e662-4baa-a837-6451849441e8">
저희 ERD 상으로 안붙어있어 안붙였는데 붙이는게 좋아보이네요. 수정하겠습니다. 감사합니다!!

2023-05-20 12:01 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +    @ManyToOne
@Icln
제 생각에 한 과목 당 여러 개의 게시판이 존재할 것 같아서 `@ManyToOne` 으로 하였는데 1 : 1로 수정하는게 좋을까요?

2023-05-20 12:24 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +public class BoardEntity {
@jiione 엔티티 명도 수정하는 것이 좋아보입니다!

2023-05-20 13:12 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +    @OneToMany(mappedBy = "board")
다시 보니까 필요 없을것 같네요 수정하겠습니다. 감사합니다!

2023-05-20 13:12 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/PostEntity.java
> +    private String view;
수정했습니다!

2023-05-20 13:13 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/PostEntity.java
> +    @JoinColumn(name = "board_id")
이 부분 단방향으로 수정하여 삭제처리 했습니다!

2023-05-20 13:14 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/SubjectsEntity.java
> +    private String credit;
저도 Integer가 더 좋을거 같아요. 수정하겠습니다.

2023-05-20 13:16 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/SubjectsEntity.java
> +    @OneToMany(mappedBy = "subjects")
단방향으로 수정했습니다.

2023-05-20 13:25 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/PostEntity.java
> +    @ManyToOne
@Icln 
fetchType에 대해서 잘 몰랐는데 덕분에 배웠습니다. 감사합니다!
이 부분은 단방향으로 변경하여 삭제했는데 대신에
`User` 테이블이나 `Subject` 테이블에 적용하여 필요하지 않은 경우에 `Course` 정보를 로딩하지 않도록 하는 것은 어떤가요?

2023-05-20 13:34 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/PostEntity.java
> +    private Timestamp time;
dateTime와 매핑되는 기본적인 java 자료형이 Timestamp라 해서 썼는데 LocalDateTime과도 되고 더 좋을것 같네요 수정하겠습니다.

2023-05-20 13:35 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/UserEntity.java
> +    private String birth;
수정하였습니다.

2023-05-20 17:24 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/PostEntity.java
> +    @ManyToOne
다른 엔티티에서도 fetchType을 Lazy로 설정하는 것이 좋아 보입니다!

2023-05-20 17:27 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/BoardEntity.java
> +    @ManyToOne
일단은 그대로 가고 후에 이부분에 대해 구현을 진행할 때 다시한번 얘기해보죠!

2023-05-20 17:29 UTC, Icln approved these changes

2023-05-20 17:29 UTC, Icln commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/Subjects.java
> +    @Column(nullable = false, length = 20)
length는 필요없는 옵션인 것 같습니다!

2023-05-21 07:05 UTC, jiione commented on src/main/java/com/SoftwareEngineering/AcademicAdmin/entity/Subjects.java
> +    @Column(nullable = false, length = 20)
수정했습니다.

2023-05-21 07:09 UTC, merged